services:
  node:
    build:
      context: .
    container_name: "psps-node"
    ports:
      - "3001:3001"
    environment:
      - SHOP=${SHOP}
      - ACCESS_TOKEN=${ACCESS_TOKEN}

  redis:
    image: redis:latest
    container_name: "psps-redis"
    ports:
      - "6379:6379"
